-- Create external table for customer data

CREATE EXTERNAL TABLE IF NOT EXISTS customers (
    customer_id STRING,
    age INT,
    gender STRING,
    location STRING,
    tenure_months INT,
    sessions_last_7_days INT,
    session_duration_avg_minutes INT,
    engagement_score DOUBLE,
    swipes_right_last_30_days INT,
    matches_last_30_days INT,
    match_success_rate DOUBLE,
    connections_sent INT,
    connections_received INT,
    total_connections INT,
    posts_last_30_days INT,
    stories_last_30_days INT,
    followers_count INT,
    following_count INT,
    profile_views_received INT,
    content_virality_score DOUBLE,
    gig_applications_sent INT,
    gig_applications_received INT,
    active_gigs_count INT,
    transaction_revenue_last_90_days DOUBLE,
    avg_job_completion_rating DOUBLE,
    influence_score DOUBLE,
    risk_score DOUBLE,
    avg_sentiment_score DOUBLE,
    network_centrality DOUBLE,
    content_diversity_score DOUBLE,
    session_consistency_score DOUBLE,
    last_7_day_engagement_trend DOUBLE,
    trust_score DOUBLE,
    response_time_avg_hours DOUBLE,
    peak_activity_hour INT,
    referral_count INT,
    time_since_first_transaction_days INT,
    premium_features_used_count INT,
    social_influence_tier STRING,
    churn_30_day INT,
    lifetime_value_usd DOUBLE,
    content_category_primary STRING
)
STORED AS PARQUET
LOCATION 's3://engagement-prediction-raw-dev/customers/';

